export const projects = [
	{
		id: 1,
		image: '/portfolioimg.png',
		title: 'Modern Frontend Portfolio Website (Next.js, TypeScript)',
		technologies: ['NextJs', 'Typescript', 'TailwindCSS', 'EmailJS'],
		liveUrl: '/',
	},
	{
		id: 2,
		image: '/hospital-finder.png',
		title: 'Hospital Locator Web App with Maps & Emergency Data',
		technologies: [
			'NextJs',
			'Typescript',
			'TailwindCSS',
			'Google Maps API',
			'Emergency Numbers API',
		],
		liveUrl: 'https://hospital-finder-eta.vercel.app/',
	},
	{
		id: 3,
		image: '/pizzacity.png',
		title: 'Restaurant Ordering Interface (React UI)',
		technologies: ['React', 'TailwindCSS', 'Javascript'],
		liveUrl: 'https://esthercate.github.io/Slice-City/',
	},
	{
		id: 4,
		image: '/sbimg.png',
		title: 'Enterprise Platform Frontend (StartupBlink)',
		technologies: ['NextJs', 'TailwindCSS', 'Typescript', 'Python'],
		liveUrl: 'https://www.startupblink.com/',
	},
	{
		id: 5,
		image: '/huddle.png',
		title: 'Responsive Marketing Landing Page (React, Bootstrap)',
		technologies: ['React', 'Bootstrap'],
		liveUrl: 'https://esthercate.github.io/huddle-landing-page/',
	},
	{
		id: 6,
		image: '/delani.png',
		title: 'Creative Agency Landing Page UI (React)',
		technologies: ['React', 'Bootstrap'],
		liveUrl: 'https://esthercate.github.io/Delani-Studio/',
	},
];
