export const projects = [
	{
		id: 1,
		image: '/portfolioimg.png',
		title: 'Personal Portfolio',
		technologies: ['NextJs', 'Typescript', 'TailwindCSS', 'EmailJS'],
		liveUrl: '/',
	},
	{
		id: 2,
		image: '/hospital-finder.png',
		title: 'Hospital Finder',
		technologies: [
			'NextJs',
			'Typescript',
			'TailwindCSS',
			'Google Maps API',
			'Emergency Numbers API',
		],
		liveUrl: 'https://hospital-finder-eta.vercel.app/',
	},
	{
		id: 3,
		image: '/pizzacity.png',
		title: 'Slice City',
		technologies: ['React', 'TailwindCSS', 'Javascript'],
		liveUrl: 'https://esthercate.github.io/Slice-City/',
	},
	{
		id: 4,
		image: '/sbimg.png',
		title: 'StartupBlink',
		technologies: ['NextJs', 'TailwindCSS', 'Typescript', 'Python'],
		liveUrl: 'https://www.startupblink.com/',
	},
	{
		id: 5,
		image: '/huddle.png',
		title: 'Huddle',
		technologies: ['React', 'Bootstrap'],
		liveUrl: 'https://esthercate.github.io/huddle-landing-page/',
	},
	{
		id: 6,
		image: '/delani.png',
		title: 'Delani Studio',
		technologies: ['React', 'Bootstrap'],
		liveUrl: 'https://esthercate.github.io/Delani-Studio/',
	},
];
